// Generated by CoffeeScript 1.2.1-pre
var ctx;

ctx = 'global';

module('coffee-script');

asyncTest('test-2', function() {
  return $.when(frame.go('')).then(function(_$) {
    var folders;
    folders = $.map(_$('li.folder'), function(el) {
      return $.trim($(el).text());
    });
    ok(folders.length > 0, "there are " + folders.length + " virtual folders");
    ok($.inArray(context.vfolder1, folders) !== -1, "" + context.vfolder1 + " is in " + folders);
    ok($.inArray(context.vfolder2, folders) !== -1, "" + context.vfolder2 + " is in " + folders);
    ok(_$('a#configure').length === 1, 'the configure button is shown');
    return start();
  });
});
